apiVersion: v1
kind: Service
metadata:
  name: postgres-ingress
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-ingress

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-ingress
    spec:
      containers:
        - name: postgres-ingress
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kongIngress
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}

