version: "3"
services:
 kong-ent-bootstrap:
  image: ${KONG_IMAGE}:${KONG_IMAGE_TAG}
  container_name: kong-ent-bootstrap
  hostname: kongBootstrap
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_PASSWORD=KongRul3z!
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres.databases
   - KONG_PG_DATABASE=kongEnterprise
   - KONG_PG_USER=kong
   - KONG_PG_PASSWORD=kong
 kong-cp:
  image: ${KONG_IMAGE}:${KONG_IMAGE_TAG}
  container_name: kong-control-plane
  hostname: kongCP
  mem_limit: 1500m
  restart: always
  ports:
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8005:8005
   - 8006:8006
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
  volumes:
   - ../shared/Kong/hybrid/:/etc/secrets/kong-hybrid-certificate/
  environment:
## RBAC    
   - KONG_PASSWORD=KongRul3z!
   - KONG_AUDIT_LOG=on
   #- KONG_ENFORCE_RBAC=on
   #- KONG_ADMIN_GUI_AUTH=basic-auth
   #- KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
## KONG MANAGER / ADMIN API
   - KONG_ADMIN_GUI_URL=http://localhost:8002
## PORTAL
   - KONG_PORTAL_GUI_HOST=localhost:8003
   - KONG_PORTAL_GUI_PROTOCOL=http
   - KONG_PORTAL=on
   - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}  
   #- KONG_PORTAL_AUTH=openid-connect
   - KONG_PORTAL_AUTH=basic-auth
## VITALS
   - KONG_VITALS=on
   - KONG_VITALS_STRATEGY=${DEMO_VITALS_STRATEGY:-database} # or 'influxdb' or 'prometheus' or 'database'
   # uncomment the below lines and comment the above to use prometheus
   - KONG_VITALS_TSDB_ADDRESS=influxdb.databases:8086
   - KONG_VITALS_STATSD_ADDRESS=statsd_exporter:9125
## LOGGING
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   #- KONG_LOG_LEVEL=debug
   - SPLUNK_HOST=kong-enterprise-node-1.localhost
## GENERAL
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_MEM_CACHE_SIZE=12M
   - KONG_NGINX_WORKER_PROCESSES=1
   - KONG_UNTRUSTED_LUA=on
## LISTENERS
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
   - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
   - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
   - KONG_STATUS_LISTEN=0.0.0.0:8100
## DATABASE
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres.databases
   - KONG_PG_DATABASE=kongEnterprise
   - KONG_PG_USER=kong
   - KONG_PG_PASSWORD=kong
## VAULT / SECRETS
   - KONG_VAULTS=bundled
   - VAULT_PLUGIN_TOKEN=KongRul3z!
## EMAILS / SMTP
   - KONG_PORTAL_EMAILS_FROM=portal@apim.eu
   - KONG_PORTAL_EMAILS_REPLY_TO=portal@apim.eu
   - KONG_SMTP_MOCK=off
   - KONG_SMTP_HOST=mail.datental.de
   - KONG_SMTP_PORT=587
   - KONG_SMTP_AUTH_TYPE=plain
   - KONG_SMTP_STARTTLS=on
   - KONG_SMTP_USERNAME=portal@apim.eu
   - 'KONG_SMTP_PASSWORD=2v.dgxb>wfoERKozHsvTMJCcY9VuVo(R'
   - KONG_SMTP_ADMIN_EMAILS=portal@apim.eu
## Manager theming
   - KONG_ADMIN_GUI_HEADER_TXT=${THEME_MGR_HEADER_TEXT}
   - KONG_ADMIN_GUI_HEADER_BG_COLOR=${THEME_MGR_HEADER_BACKGROUND_COLOR}
   - KONG_ADMIN_GUI_HEADER_TXT_COLOR=${THEME_MGR_HEADER_TEXT_COLOR}
   - KONG_ADMIN_GUI_FOOTER_TXT=${THEME_MGR_FOOTER_TEXT}
   - KONG_ADMIN_GUI_FOOTER_BG_COLOR=${THEME_MGR_FOOTER_BACKGROUND_COLOR}
   - KONG_ADMIN_GUI_FOOTER_TXT_COLOR=${THEME_MGR_FOOTER_TEXT_COLOR}
   - KONG_ADMIN_GUI_LOGIN_BANNER_TITLE=${THEME_MGR_LOGIN_BANNER_TITLE}
   - KONG_ADMIN_GUI_LOGIN_BANNER_BODY=${THEME_MGR_LOGIN_BANNER_BODY}
## Hybrid
   - KONG_ROLE=control_plane
   - KONG_CLUSTER_CERT=/etc/secrets/kong-hybrid-certificate/cluster.crt
   - KONG_CLUSTER_CERT_KEY=/etc/secrets/kong-hybrid-certificate/cluster.key
   - KONG_CLUSTER_LISTEN=0.0.0.0:8005
   - KONG_CLUSTER_TELEMETRY_LISTEN=0.0.0.0:8006