apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  ports:
  - name: httpbin
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: httpbin

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: svenwal/httpbin
