apiVersion: v1
kind: Service
metadata:
  name: placeholder
spec:
  ports:
  - name: placeholder-port
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: placeholder

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: placeholder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: placeholder
          image: svenwal/jsonplaceholder
