---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-mesh-tcp
spec:
  ports:
  - name: filebeat-mesh-tcp
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: filebeat-mesh


---
apiVersion: v1
kind: ReplicationController
metadata:
  name: filebeat-mesh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat-mesh
    spec:
      containers:
        - name: filebeat-mesh
          image: docker.elastic.co/beats/filebeat:7.9.3
          args: [
              "-e"
            ]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: filebeat-mesh-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
          - name: elasticsearchtemplate
            mountPath: /usr/share/filebeat/elasticsearch_template.json
            subPath: elasticsearch_template.json
          ports:
            - containerPort: 9001
              name: tcp
              protocol: TCP
      volumes:
        - name: filebeat-mesh-config
          configMap:
            name: filebeat-mesh-config
            items:
            - key: filebeat.yml
              path: filebeat.yml
        - name: elasticsearchtemplate
          configMap:
            name: filebeat-mesh-config
            items:
            - key: elasticsearch_template.json
              path: elasticsearch_template.json
