apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog
  template:
    metadata:
      labels:
        app: datadog
    spec:
      containers:
        - name: datadog
          image: datadog/agent:latest
          env:
            - name: DD_API_KEY
              value: ${DD_API_KEY}
            - name: DD_HOSTNAME
              value: datadog
            - name: DD_SITE
              value: datadoghq.com
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_BIND_HOST
              value: "0.0.0.0"
