apiVersion: v1
kind: Service
metadata:
  name: graylog-ui
spec:
  type: NodePort
  ports:
  - name: graylog-ui
    port: 9000
    targetPort: 9000
    nodePort: 31140
    protocol: TCP
  selector:
    app: graylog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:4.0
          command: ["/usr/bin/tini -- wait-for-it elasticsearch.monitoring:9200 --  /docker-entrypoint.sh"]
          env:
            - name: GRAYLOG_MONGODB_URI
              value: "mongodb.databases://mongo/graylog"
            - name: GRAYLOG_PASSWORD_SECRET
              value: "somepasswordjepcme"
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "http://localhost:9140/"