apiVersion: v1
kind: Service
metadata:
  name: syslog-ui
spec:
  type: NodePort
  ports:
  - name: syslog-ui
    port: 80
    targetPort: 80
    nodePort: 31130
    protocol: TCP
  selector:
    app: syslog

---
apiVersion: v1
kind: Service
metadata:
  name: syslog
spec:
  ports:
  - name: syslog
    port: 514
    targetPort: 514
    protocol: UDP
  selector:
    app: syslog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog
  template:
    metadata:
      labels:
        app: syslog
    spec:
      containers:
        - name: syslog
          image: pbertera/syslogserver
          env:
            - name: SYSLOG_USERNAME
              value: kong
            - name: SYSLOG_PASSWORD
              value: kong
            - name: CHECK_UPGRADE
              value: "false"
            - name: EXPORT
              value: "true"