apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    80.service.kuma.io/protocol: http
spec:
  ports:
  - name: frontend
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: svenwal/bankong-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BANKONG_TRANSACTIONS_BACKEND_URL
              value: "http://backend-transactions.bankong:3000"
            - name: BANKONG_ORDERS_BACKEND_URL
              value: "http://backend-orders.bankong:3000"
