apiVersion: v1
kind: Secret
metadata:
  name: kong-license
stringData:
  KONG_LICENSE_DATA: '{ "license": { "version": 1, "signature": "d63f5f8e38006cd61ef7d82747e99e30616869dd08af28df0682cd86fc4dfb1dd655880a526eb1585401d653c4dbe188fa2d8e13d8165a47eab0f10063e55e9a", "payload": { "customer": "Kong Inc. SEs", "license_creation_date": "2022-05-18", "product_subscription": "Kong Enterprise Subscription", "support_plan": "Platinum", "admin_seats": "1", "dataplanes": "1000", "license_expiration_date": "2023-06-30", "license_key": "0011K000022IA3HQAW_a1V1K000007KlJMUA0" } } }'

---

apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-license
stringData:
  license: '{ "license": { "version": 1, "signature": "d63f5f8e38006cd61ef7d82747e99e30616869dd08af28df0682cd86fc4dfb1dd655880a526eb1585401d653c4dbe188fa2d8e13d8165a47eab0f10063e55e9a", "payload": { "customer": "Kong Inc. SEs", "license_creation_date": "2022-05-18", "product_subscription": "Kong Enterprise Subscription", "support_plan": "Platinum", "admin_seats": "1", "dataplanes": "1000", "license_expiration_date": "2023-06-30", "license_key": "0011K000022IA3HQAW_a1V1K000007KlJMUA0" } }}'
