kuma:
  controlPlane:
    service:
      type: NodePort
      port: "31800"
    secrets:
      - Env: "KMESH_LICENSE_INLINE"
        Secret: "kong-mesh-license"
        Key: "license.json"
  global:
    image:
      tag: "1.8.1"
