version: "3"
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-beta1
  container_name: elasticsearch.monitoring
  environment: 
   - discovery.type=single-node
   - xpack.security.enabled=false
   - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  ports:
   - 8111:9200
 kibana:
  image: docker.elastic.co/kibana/kibana:8.0.0-beta1
  container_name: kibana.monitoring
  depends_on:
   - elasticsearch
  ports: 
   - 8110:5601
 filebeat:
  image: docker.elastic.co/beats/filebeat:8.0.0-beta1
  container_name: filebeat.monitoring
  user: root
  depends_on:
   - elasticsearch
  command: ["--strict.perms=false"]
  volumes:
   - ../shared/Monitoring/cfg/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
   - ../shared/Monitoring/cfg/elk/elasticsearch_template.json:/usr/share/filebeat/elasticsearch_template.json

