version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  graylog:
    image: graylog/graylog:4.0
    environment:
      - GRAYLOG_MONGODB_URI=mongodb://mongo/graylog
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordjepcme
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:8140/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch.monitoring:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
    ports:
      # Graylog web interface and REST API
      - 8140:9000
      # Syslog TCP
      #- 1514:1514
      # Syslog UDP
      #- 1514:1514/udp
      # GELF TCP
      #- 12201:12201
      # GELF UDP
      #- 12201:12201/udp
