version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.6
    container_name: zookeeper.backends
    environment:  
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:2.3.1
    container_name: kafka.backends
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9082:9082
