version: "3"
services:
 kong-ent2:
  image: ${KONG_IMAGE:-kong/kong-gateway}:${KONG_IMAGE_TAG:-latest}
  container_name: kong-ent2
  hostname: kongNode2
  mem_limit: 1000m
  depends_on:
   - kong-ent1
  restart: always
  ports:
   - 8010:8000
   - 8017:8018/udp
   - 8453:8443
   - 8018:9080
   - 8019:9081
  volumes:
   - ../shared/Kong/hybrid/:/etc/secrets/kong-hybrid-certificate/
  environment:
   - KONG_PORTAL=off
   - KONG_VAULTS=off
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_STATUS_LISTEN=0.0.0.0:8100
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres.databases
   - KONG_PG_DATABASE=kongEnterprise
   - KONG_PG_USER=kong
   - KONG_PG_PASSWORD=kong
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_STREAM_LISTEN=0.0.0.0:8018 udp
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_LUA_PACKAGE_PATH=/opt/sigsci/nginx/sigsci-module-nginx/?.lua
   - KONG_VITALS=on
   - KONG_VITALS_STRATEGY=${DEMO_VITALS_STRATEGY:-database}
   - KONG_VITALS_TSDB_ADDRESS=influxdb.databases:8086
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - SPLUNK_HOST=kong-enterprise-node-2.localhost
   - KONG_MEM_CACHE_SIZE=12M
   - KONG_NGINX_WORKER_PROCESSES=1
   - KONG_UNTRUSTED_LUA=on
 kong-ent3:
  image: ${KONG_IMAGE:-kong/kong-gateway}:${KONG_IMAGE_TAG:-latest}
  container_name: kong-ent3
  hostname: kongNode3
  mem_limit: 1000m
  depends_on:
   - kong-ent1
  restart: always
  ports:
   - 8020:8000
   - 8028:8028/udp
   - 8463:8443
   - 8028:9080
   - 8029:9081
  volumes:
   - ../shared/Kong/hybrid/:/etc/secrets/kong-hybrid-certificate/
  environment:
   - KONG_PORTAL=off
   - KONG_VAULTS=off
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_STATUS_LISTEN=0.0.0.0:8100
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres.databases
   - KONG_PG_DATABASE=kongEnterprise
   - KONG_PG_USER=kong
   - KONG_PG_PASSWORD=kong
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_STREAM_LISTEN=0.0.0.0:8028 udp
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_LUA_PACKAGE_PATH=/opt/sigsci/nginx/sigsci-module-nginx/?.lua
   - KONG_VITALS=on
   - KONG_VITALS_STRATEGY=${DEMO_VITALS_STRATEGY:-database}
   - KONG_VITALS_TSDB_ADDRESS=influxdb.databases:8086
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - SPLUNK_HOST=kong-enterprise-node-3.localhost
   - KONG_MEM_CACHE_SIZE=12M
   - KONG_NGINX_WORKER_PROCESSES=1
   - KONG_UNTRUSTED_LUA=on
