version: "3"
services:
 kong-dp1:
  image: ${KONG_IMAGE}:${KONG_IMAGE_TAG}
  container_name: kong-dataplane-1
  hostname: kongDP1
  mem_limit: 1000m
  depends_on:
   - kong-cp
  restart: always
  ports:
   - 8000:8000
   - 8007:8008/udp
   - 8443:8443
   - 9080:9080
   - 8009:9081
  volumes:
   - ../shared/Kong/hybrid/:/etc/secrets/kong-hybrid-certificate/
  environment:
   - KONG_ROLE=data_plane
   - KONG_CLUSTER_CERT=/etc/secrets/kong-hybrid-certificate/cluster.crt
   - KONG_CLUSTER_CERT_KEY=/etc/secrets/kong-hybrid-certificate/cluster.key
   - KONG_CLUSTER_CONTROL_PLANE=kong-control-plane:8005
   - KONG_CLUSTER_TELEMETRY_ENDPOINT=kong-control-plane:8006
   - KONG_PORTAL=off
   - KONG_VAULTS=bundled
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_STATUS_LISTEN=0.0.0.0:8100
   - KONG_DATABASE=off
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_STREAM_LISTEN=0.0.0.0:8008 udp
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_LUA_PACKAGE_PATH=/opt/sigsci/nginx/sigsci-module-nginx/?.lua
   - KONG_VITALS=on
   - KONG_VITALS_STRATEGY=${DEMO_VITALS_STRATEGY:-database}
   - KONG_VITALS_TSDB_ADDRESS=influxdb.databases:8086
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - SPLUNK_HOST=kong-enterprise-node-2.localhost
   - KONG_MEM_CACHE_SIZE=12M
   - KONG_NGINX_WORKER_PROCESSES=1
   - KONG_UNTRUSTED_LUA=on
 kong-dp2:
  image: ${KONG_IMAGE}:${KONG_IMAGE_TAG}
  container_name: kong-dataplane-2
  hostname: kongDP2
  mem_limit: 1000m
  depends_on:
   - kong-cp
  restart: always
  ports:
   - 8010:8000
   - 8020:8000
   - 8018:8028/udp
   - 8453:8443
   - 8018:9080
   - 8019:9081
  volumes:
   - ../shared/Kong/hybrid/:/etc/secrets/kong-hybrid-certificate/
  environment:
   - KONG_ROLE=data_plane
   - KONG_CLUSTER_CERT=/etc/secrets/kong-hybrid-certificate/cluster.crt
   - KONG_CLUSTER_CERT_KEY=/etc/secrets/kong-hybrid-certificate/cluster.key
   - KONG_CLUSTER_CONTROL_PLANE=kong-control-plane:8005
   - KONG_CLUSTER_TELEMETRY_ENDPOINT=kong-control-plane:8006
   - KONG_PORTAL=off
   - KONG_VAULTS=bundled
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_STATUS_LISTEN=0.0.0.0:8100
   - KONG_DATABASE=off
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_STREAM_LISTEN=0.0.0.0:8028 udp
   - KONG_PLUGINS=${DEMO_ENABLED_PLUGINS:-bundled}
   - KONG_LUA_PACKAGE_PATH=/opt/sigsci/nginx/sigsci-module-nginx/?.lua
   - KONG_VITALS=on
   - KONG_VITALS_STRATEGY=${DEMO_VITALS_STRATEGY:-database}
   - KONG_VITALS_TSDB_ADDRESS=influxdb.databases:8086
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - SPLUNK_HOST=kong-enterprise-node-3.localhost
   - KONG_MEM_CACHE_SIZE=12M
   - KONG_NGINX_WORKER_PROCESSES=1
   - KONG_UNTRUSTED_LUA=on
