version: "3"
services:
 grafana:
  image: grafana/grafana
  container_name: grafana.monitoring
  volumes:
    - ../shared/Monitoring/cfg/grafana/:/etc/grafana/provisioning/
  ports:
   - 8100:3000
  environment:
   - GF_AUTH_ANONYMOUS_ENABLED=true
 prometheus:
  image: prom/prometheus
  container_name: prometheus.monitoring
  hostname: prometheus
  volumes:
   - ../shared/Monitoring/cfg/prometheus.yml:/etc/prometheus/prometheus.yml
  command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
  ports:
   - 8101:9090
