apiVersion: v1
kind: Service
metadata:
  name: opa
spec:
  type: NodePort
  ports:
  - name: opa
    port: 8181
    targetPort: 8181
    nodePort: 31303
    protocol: TCP
  selector:
    app: opa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--log-level"
            - "debug"


