apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: bankong
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "bankong.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: 
              number: 80
