apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-test-bankong-frontend
  namespace: test
config:
  replace:
    uri: /cross-mesh/test/bankong-frontend
plugin: request-transformer-advanced
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-to-test-mesh
  namespace: test
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: request-transformer-test-bankong-frontend
spec:
  rules:
  - host: "bankong.test.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-enterprise-test-proxy
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-test
  namespace: test
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
spec:
  rules:
  - http:
      paths:
      - path: /cross-mesh/test/bankong-frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
