apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "elk.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch
            port: 
              number: 9200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "kibana.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port: 
              number: 5601
