apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syslog
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "syslog.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: syslog-ui
            port: 
              number: 80
