apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin
  namespace: tracing
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "zipkin.service-connectivity.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zipkin
            port: 
              number: 9411
