apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kong-se-central-demo
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      allow: true
