apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kong-se-central-control-plane
  region: eu-west-3

nodeGroups:
  - name: control-plane-ng
    instanceType: m5.large
    desiredCapacity: 1
    ssh:
      allow: true
