image:
  repository: kong/kong-gateway
  tag: "2.8.1.2"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: a6d0f08bd8.us.cp0.konghq.com:443
  cluster_server_name: a6d0f08bd8.us.cp0.konghq.com
  cluster_telemetry_endpoint: a6d0f08bd8.us.tp0.konghq.com:443
  cluster_telemetry_server_name: a6d0f08bd8.us.tp0.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system

ingressController:
  enabled: false
  installCRDs: false
