apiVersion: v1
kind: Service
metadata:
  name: backend-transactions
  annotations:
    3000.service.kuma.io/protocol: http
spec:
  ports:
  - name: backend-transactions
    targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    app: backend-transactions

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-transactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-transactions
  template:
    metadata:
      labels:
        app: backend-transactions
    spec:
      containers:
        - name: backend-transactions
          image: svenwal/bankong-backend-transactions:0.3.1
          env:
            - name: BACKEND_REGION
              value: us-central1
            - name: BACKEND_DATACENTER
              value: Google Cloud
            - name: BACKEND_ARCHITECTURE
              value: Kubernetes
            - name: BACKEND_FLAG
              value: 🇺🇸
            - name: BACKEND_LOGO_URL
              value: https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Google_Cloud_logo.svg/320px-Google_Cloud_logo.svg.png
          ports:
            - containerPort: 3000
