apiVersion: v1
kind: Service
metadata:
  name: example
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: NodePort
  ports:
  - name: example
    targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    app: example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
        cloud: "yes"
    spec:
      containers:
        - name: example
          image: svenwal/httpbin
          ports:
            - containerPort: 8080
