apiVersion: v1
kind: Service
metadata:
  name: grpcbin
  annotations:
    ingress.kubernetes.io/service-upstream: "true"  
spec:
  ports:
  - name: grpcbin
    targetPort: 9000
    port: 9000
    protocol: TCP
  selector:
    app: grpcbin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      containers:
        - name: grpcbin
          image: moul/grpcbin
          ports:
            - containerPort: 9000
            - containerPort: 9001
