apiVersion: v1
kind: Service
metadata:
  name: certificates
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: NodePort
  ports:
  - name: certificates
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: upstream-tls

---
apiVersion: v1
kind: Service
metadata:
  name: upstream-tls
  annotations:
    konghq.com/protocol: https
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: NodePort
  ports:
  - name: upstream-tls
    targetPort: 443
    port: 443
    nodePort: 31904
    protocol: TCP
  selector:
    app: upstream-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upstream-tls
  template:
    metadata:
      labels:
        app: upstream-tls
    spec:
      containers:
        - name: upstream-tls
          image: svenwal/mtlsserver:0.3
          ports:
            - containerPort: 80
            - containerPort: 443
