apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mj-test-v3-merck
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      allow: true
