# Basic configuration for Kong Enterprise without the ingress controller, using the Postgres subchart
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001
# Before installing:
# * Several settings (search for the string "CHANGEME") require user-provided
#   Secrets. These Secrets must be created before installation.
# * Ensure that your session configurations create cookies that are usable
#   across your services. The admin session configuration must create cookies
#   that are sent to both the admin API and Kong Manager, and any Dev Portal
#   instances with authentication must create cookies that are sent to both
#   the Portal and Portal API.
image:
  repository: kong/kong-gateway
  tag: "latest"
env:
  database: postgres
  pg_host: hostname.rds.amazonaws.com # CHANGEME
  pg_user: kong # CHANGEME
  pg_database: postgres # CHANGEME
  pg_password: example-password # CHANGEME
  password:
    valueFrom:
      secretKeyRef:
        key: kong_admin_password
        name: kong-config-secret
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  admin_api_uri: http://example.elb.amazonaws.com:8001 # CHANGEME
  admin_gui_url: http://example.eu-west-2.elb.amazonaws.com:8002 # CHANGEME
admin:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
manager:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
cluster:
  enabled: true
  type: LoadBalancer
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
clustertelemetry:
  enabled: true
  type: LoadBalancer
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006
proxy:
  enabled: false
secretVolumes:
  - kong-cluster-cert 
postgresql:
  enabled: false
ingressController:
  enabled: false
enterprise:
  enabled: true
  vitals:
    enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    admin_gui_auth_conf_secret: kong-config-secret
    session_conf_secret: kong-config-secret
portal:
  enabled: false
portalapi:
  enabled: false
